name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      test_env:
        description: "Environment to run tests against"
        required: true
        type: choice
        default: qa
        options:
          - qa
          - dev
      browser:
        description: "Browser to run tests against"
        required: true
        type: choice
        default: chromium
        options:
          - chromium
          - firefox
          - webkit
      test_tags:
        description: "Test tags to filter tests"
        required: false
        type: choice
        default: "@playwrightDemo"
        options:
          - "@playwrightDemo"
          - "@pomDemo"
          - "@fixtureDemo"
      parallel:
        description: "Workers for running tests in parallel"
        required: true
        type: choice
        default: "1"
        options:
          - "1"
          - "2"
          - "3"
permissions:
  contents: write # Allow read/write access to repository contents (for pushing code)
  issues: write # Allow read/write access to issues (create/edit)
  pull-requests: read # Allow read access to pull requests information

jobs:
  playwright_test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: 1. Install dependencies
        run: npm ci
      - name: 2. Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: 3. Init workflow variables
        env:
          DEFAULT_ENV: "qa"
          DEFAULT_BROWSER: "chromium"
          DEFAULT_PARALLEL: 1
          DEFAULT_TEST_TAGS: "@playwrightDemo"
        run: |
          echo "TEST_ENV=${{ inputs.test_env || env.DEFAULT_ENV }}" >> $GITHUB_ENV
          echo "TEST_BROWSER=${{ inputs.browser || env.DEFAULT_BROWSER }}" >> $GITHUB_ENV
          echo "TEST_PARALLEL=${{ inputs.parallel || env.DEFAULT_PARALLEL }}" >> $GITHUB_ENV
          echo "TEST_TAGS=${{ inputs.test_tags || env.DEFAULT_TEST_TAGS }}" >> $GITHUB_ENV
      - name: 4. Set up workflow variables
        run: |
          export NODE_ENV=${{ env.TEST_ENV }}
          echo ">>>>>> Test environment is: $NODE_ENV"
          echo ">>>>>> Test browser is: ${{ env.TEST_BROWSER }}"
          echo ">>>>>> Test parallel is: ${{ env.TEST_PARALLEL }}"
      - name: 5. Run Playwright tests
        run: |
          npx playwright test --project=${{ env.TEST_BROWSER }} --grep=${{ env.TEST_TAGS }} --workers=${{ env.TEST_PARALLEL }}
      - name: 6. Load Allure test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir
      - name: 7. Generate Allure test report
        uses: andgineer/allure-report@v3.5
        id: allure-report
        if: always()
        with:
          allure-results: allure-results
          website: gh-pages-dir
          reports-site-path: builds/tests
          report-page: behaviors
      - name: 8. Publish Allure test report
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ always() && (steps.allure-report.outcome == 'success') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.allure-report.outputs.reports-site }}
          destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}
